import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  topContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    margin: 26,
    marginTop: 60,
    height: "7%",
  },
  back: {
    position: "absolute",
    fontSize: 16,
    fontWeight: "500",
    color: "rgb(93, 176, 117)",
    textAlign: "left",
    width: 38,
    height: 19,
    marginTop: 8,
  },
  filter: {
    marginTop: 8,
    position: "absolute",
    fontSize: 16,
    fontWeight: "500",
    color: "rgb(93, 176, 117)",
    textAlign: "right",
    left: "89%",
    width: 39,
    height: 19,
  },
  cont: {
    position: "absolute",
    fontSize: 30,
    fontWeight: "600",
    textAlign: "center",
    width: 118,
    height: 36,
    left: "35%",
  },
  searchbar: {
    width: 393,
    height: 50,
    position: "absolute",
    borderWidth: 1,
    borderColor: "rgb(232, 232, 232)",
    borderRadius: 100,
    backgroundColor: "rgb(246, 246, 246)",
    padding: 10,
    color: "gray",
    paddingLeft: 20,
  },
  search: {
    marginTop: 60,
    position: "relative",
    width: 363,
  },
});
